#!/bin/zsh
CUSTOM_DIR="~/.oh-my-zsh/custom"

[[ -n "$ZSH_CUSTOM" ]] && CUSTOM_DIR=$ZSH_CUSTOM

CUSTOM_DIR+="/themes"

START_DIR=`pwd`

mkdir -p $CUSTOM_DIR

cd $CUSTOM_DIR

git clone https://github.com/ariporad/zsh-theme.git ariporad-theme

ln -s ariporad-theme/ariporad.zsh-theme ariporad.zsh-theme

cat ~/.zshrc > ~/.zshrc.pre-ariporad
echo "\n\n### Autogenerated installation for https://github.com/ariporad/zsh-theme. ###\nZSH_THEME=\"ariporad\"\n### END ###\n" >> ~/.zshrc

echo "ariporad theme installed to $CUSTOM_DIR/ariporad-theme and symlinked to $CUSTOM_DIR/ariporad.zsh-theme. ~/.zshrc backed up to ~/.zshrc.pre-ariporad. Re-loading ~/.zshrc".

source ~/.zshrc

cd $START_DIR

